name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "latest"
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --no-interaction

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test tests/Unit
